config/routes.rb
Rails.application.routes.draw do

  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'
  get 'now_following' => 'epicenter#now_following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'all_users' => 'epicenter#all_users'
  get 'tag_chirps' => 'epicenter#tag_chirps'
  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'


  resources :chirps
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chirp.rb
class Chirp < ApplicationRecord
	belongs_to :user

	has_many :chirp_tags
    has_many :tags, through: :chirp_tags

    before_validation :link_check, on: :create

	validates :message, presence: true 
  	validates :message, length: {maximum: 140, too_long: "A chirp is only 140 max. Everybody knows that!"}, on: :create


  	after_validation :apply_link, on: :create

  private

		  def link_check
		  	check = false
		  	if (self.message.include?("https://")) || (self.message.include?("http://")) || (self.message.include?("www."))
		  		check = true
		  	end

		  	if check == true
		    	arr = self.message.split

		      if self.message.include?("http")
		        index = arr.map{ |x| x.include? "http"}.index(true)
		        self.link = arr[index]
		      elsif self.message.include?("www")
		        index = arr.map{ |x| x.include? "www"}.index(true)
		        self.link = "https://#{arr[index]}"
		      end
		    	
		      
		        
		        if arr[index].length > 23
		    	    arr[index] = "#{arr[index][0..19]}..."	
		        end
		    				
		        self.message = arr.join(" ")
		      end
		  end#def link_check

		  def apply_link
		  	arr = self.message.split
		  	index = arr.map{|x| x.include? "http"}.index(true)
		    index = arr.map{ |x| x.include? "www"}.index(true)

		  	if index
		  		url = arr[index]
		  		arr[index] = "<a href='#{self.link}' target='_blank'>#{url} </a> "
		  	end#if

		  	self.message = arr.join(" ")
		  end#apply_link





end

app/models/chirp_tag.rb
class ChirpTag < ApplicationRecord
	belongs_to :chirp
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :chirp_tags
    has_many :chirps, through: :chirp_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :chirps
  has_one_attached :avatar
    serialize :following, Array

  validates :username, presence: true
  validates :username, uniqueness: true

  def avatar_thumbnail
  	if avatar.attached?
  		avatar.variant(resize: "25x25!").processed
  	else
  		'/default_avatar.png'
  end

  private

  	def add_default_avatar
  		unless avatar.attached?
  			avatar.attach(
  				io: File.open(
  					Rails.root.join(
  						'app','assets', 'images', 'default_avatar.png'
  						)
  					), filename: 'default_avatar.png',
  				content_type: 'image/png'
  				)
  			
  		end
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :avatar, :bio, :location, :following])
  end
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  include ChirpsHelper

  # GET /chirps
  # GET /chirps.json
  def index
    @chirps = Chirp.all
  end

  # GET /chirps/1
  # GET /chirps/1.json
  def show
  end

  # GET /chirps/new
  def new
    @chirp = Chirp.new
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  # POST /chirps.json
  def create
    @chirp = Chirp.create(chirp_params)
    @chirp = get_tagged(@chirp)

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to @chirp, notice: 'Chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chirps/1
  # PATCH/PUT /chirps/1.json
  def update
    respond_to do |format|
      if @chirp.update(chirp_params)
        format.html { redirect_to @chirp, notice: 'Chirp was successfully updated.' }
        format.json { render :show, status: :ok, location: @chirp }
      else
        format.html { render :edit }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chirps/1
  # DELETE /chirps/1.json
  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'Chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chirp_params
      params.require(:chirp).permit(:message, :user_id, :link)
    end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
	before_action :authenticate_user!, except: [:feed]

  def feed
  	@chirp = Chirp.new

    if user_signed_in?
	  	@following_chirps = []

	    Chirp.all.each do |chirp|
		      if current_user.following.include?(chirp.user_id) || current_user.id == chirp.user_id
		        @following_chirps.push(chirp)
		      end
	    end
	else
      redirect_to chirps_path
    end    
  end

  def show_user
  	@user = User.find(params[:id])
  	@chirp = Chirp.new
  end

  def now_following
  # Adding the user.id of the user you want to 
  # follow to your following array.
  # This makes sure it's saved in there as an integer
  current_user.following.push(params[:id].to_i)
  current_user.save

  redirect_to show_user_path(id: params[:id])
  end

  def all_users
  	@users = User.all
  end

  def unfollow
  current_user.following.delete(params[:id].to_i)
  current_user.save

  redirect_to show_user_path(id: params[:id]) 
  end
  
  def tag_chirps
	@tag = Tag.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @user =  User.find(params[:id])
    @users = []

    User.all.each do |user|
      if user.following.include?(@user.id)
        @users.push(user)
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chirps_helper.rb
module ChirpsHelper
	def get_tagged(chirp)
		message_arr = Array.new
    	message_arr = @chirp.message.split

	    message_arr.each_with_index do |word, index|
	      if word[0] == "#"
	        if Tag.pluck(:phrase).include?(word.downcase)
	          #save that Tag as a variable (to use in ChirpTag creation)
	          tag = Tag.find_by(phrase: word.downcase)
	        else
	          #create a new instance of Tag
	          tag = Tag.create(phrase: word.downcase)
	        end
	        chirp_tag = ChirpTag.create(chirp_id: @chirp.id, tag_id: tag.id)
	        message_arr[index] = "<a href='/tag_chirps?id=#{tag.id}'>#{word}</a>"
	      end
	    end
	    @chirp.update(message: message_arr.join(" "))
	    return chirp
	end
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/views/chirps/_form.html.erb
<%= form_with(model: chirp) do |form| %>
  <% if chirp.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(chirp.errors.count, "error") %> prohibited this chirp from being saved:</h2>

        <ul>
          <% chirp.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>



<div class="row">
      <div class="col-3">
          
          <div class="form-group">
          <%= form.text_area :message, placeholder: "What's on your mind?", class:"form-control"%>
          </div>
          
          <div class="col">
            <div class="field">
              <%= form.hidden_field :user_id, value: current_user.id %>
            </div>
          </div>
          
      
      </div>
</div>

<div class="row">
  <div class="col auto">
    <div class="actions">
         <%= form.submit "Chirp it!", class: "btn btn-success btn-lg"%>
     </div>
  </div>
     
</div>
      

      
  
<% end %>

app/views/chirps/edit.html.erb
<h1>Editing Chirp</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Show', @chirp, class: "btn btn-info btn-sm" %> |
<%= link_to 'Back', chirps_path, class: "btn btn-primary btn-sm" %>

app/views/chirps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chirps</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>User</th>
      <th>Messages</th>
    </tr>
  </thead>

  <tbody>
    <% @chirps.each do |chirp| %>
      <tr>
          <td>
            <% if chirp.user.avatar.attached? %>
                    <%= image_tag (chirp.user.avatar.variant(resize_to_limit: [50,50]))%>
                  <% else %>
                    <%= image_tag("default_avatar.png", :size=>"50x50")%> 
                  <% end%>
          </td>
          <td>@<%= link_to chirp.user.username, show_user_path(id: chirp.user.id) %></td> 
         
          <td><%= link_to chirp.message.html_safe , chirp %></td>
          <%if user_signed_in? && current_user.id == chirp.user.id %>
            <td><%= link_to image_tag("edit.png", :size=>"20x20"), edit_chirp_path(chirp) %></td>
            <td><%= link_to image_tag("trashcan.png", :size=>"20x20"), chirp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
          
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chirp', new_chirp_path %>

app/views/chirps/new.html.erb
<h1>New Chirp</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Back', chirps_path, class: "btn btn-primary btn-sm" %>

app/views/chirps/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="d-flex align-items-center">
	        <div class="row my-3 " style="background-color: #ebf2ff; width: 500px">
		        	<div class="col-xs mx-3 my-2">
			        	<% if @chirp.user.avatar.attached? %>
		                        <%= image_tag (chirp.user.avatar.variant(resize_to_limit: [50,50]))%>
		                      <% else %>
		                        <%= image_tag("default_avatar.png", :size=>"50x50")%> 
		                <% end%>
	                </div>
			        
				    <div class="col-xs align-self-center">
				    	<p >@<%= @chirp.user.username %>
	                    <%= time_ago_in_words(@chirp.created_at) if Time.now - @chirp.created_at < 86400 %> 
	                    <%= @chirp.created_at.strftime('%b %e') if Time.now - @chirp.created_at > 86400 %>
		        		</p>
				    </div>
				    <div class="col-5 ml-3 my-2" style="width: 450px; background-color: #e1e8f5"><%= @chirp.message.html_safe %></div>
				   
				</div> 
			</div>

<%if user_signed_in? && current_user.id == @chirp.user.id %>
<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<% end %>
<%= link_to 'Back', chirps_path, class: "btn btn-primary btn-sm" %>

app/views/epicenter/_user_list.html.erb
 <table class="table table-hover table-striped">
  <thead>
    <tr>
      <th scope="col">User Pic</th>
      <th scope="col">User</th>
      <th scope="col">Following Status</th>
      <th scope="col">Bio</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
          
            <td>
              <% if user.avatar.attached? %>
                      <%= image_tag (user.avatar.variant(resize_to_limit: [50,50]))%>
                    <% else %>
                      <%= image_tag("default_avatar.png", :size=>"50x50")%> 
                    <% end%>
            </td>
          
            <td>
              <%= link_to show_user_path(id: user.id) do %>
              <strong><%= user.name %></strong>
              <p>@<%= user.username %></p>
            <% end %>
            </td>
            <td>
              <p>
                <% if current_user.following.include?(user.id) %>
                  <%= link_to "Unfollow", unfollow_path(id: user.id), class: "btn btn-danger", id: "unfollow_btn" %>
                <% else %>
                  <% if current_user.id != user.id %>
                    <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
                  <% end %>
                <% end %>
              </p>
            </td>

          <td>
            <p>
              <%= user.bio %>
            </p>
          </td>
      
      </tr>
    <% end %>
  </tbody>
</table>

app/views/epicenter/all_users.html.erb
<h1>These are all the current Users:</h1>
<div>
    <%=render 'user_list' %>
</div>

app/views/epicenter/feed.html.erb
<h1>@<%= current_user.username %>'s Chirp Feed</h1>


<br>
<div>
    <%= render 'chirps/form', chirp: @chirp %>
</div>
<br>

<p><strong>Here is what your "friends" are saying:</strong></p>

<div class="row">
	<div class="col-4"></div>
	<div class="col-8">
	    <% @following_chirps.reverse_each do |chirp| %>
	    <div class="d-flex align-items-center">
	        <div class="row my-3 " style="background-color: #ebf2ff; width: 500px">
		        	<div class="col-xs mx-3 my-2">
			        	<% if chirp.user.avatar.attached? %>
		                        <%= image_tag (chirp.user.avatar.variant(resize_to_limit: [50,50]))%>
		                      <% else %>
		                        <%= image_tag("default_avatar.png", :size=>"50x50")%> 
		                <% end%>
	                </div>
			        
				    <div class="col-xs align-self-center">
				    	<p >@<%= chirp.user.username %>
	                    <%= time_ago_in_words(chirp.created_at) if Time.now - chirp.created_at < 86400 %> 
	                    <%= chirp.created_at.strftime('%b %e') if Time.now - chirp.created_at > 86400 %>
		        		</p>
				    </div>
				    <div class="col-5 ml-3 my-2" style="width: 450px; background-color: #e1e8f5"><%= chirp.message.html_safe %>
				    	<%if user_signed_in? && current_user.id == chirp.user.id %>
				            <%= link_to image_tag("edit.png", :size=>"20x20"), edit_chirp_path(chirp) %>
				            <%= link_to image_tag("trashcan.png", :size=>"20x20"), chirp, method: :delete, data: { confirm: 'Are you sure?' } %>
            			<%end%>
				    </div>
				   
				</div> 
			</div>
	    <% end %>
	</div>
</div>

app/views/epicenter/followers.html.erb
<h2>Here's whose following <%= @user.username%> </h2>
<div>
    <%=render 'user_list' %>
</div>

app/views/epicenter/following.html.erb
<!-- following.html.erb -->
<h2><%= @user.name %> is following:</h2>
<%= render 'user_list' %>

app/views/epicenter/now_following.html.erb
<h1>Epicenter#now_following</h1>
<p>Find me in app/views/epicenter/now_following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1 class="text-center">@<%= @user.username %>'s Profile & Chirps</h1>
<br>
<br>


<div class="container">
        <div class="row row-cols-3">
        	<div class="col">
        		<% if @user.avatar.attached? %>
                        <%= image_tag (@user.avatar.variant(resize_to_limit: [250,250]))%>
                      <% else %>
                        <%= image_tag("default_avatar.png", :size=>"250x250")%> 
                      <% end%>
        	</div>
        	<div class="col"></div>
        	<div class="col"></div>    
        </div>
        <div class="container">
            <h4 class="row">
            	<%=@user.name %>		
            </h4>
            <p> Location: <%=@user.location %></p>
            <p> Bio: <%= @user.bio %></p>

            <p>
                <% if current_user.following.include?(@user.id) %>
                    <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary text-white", id: "unfollow_btn" %>
                <% else %>
                    <% if current_user.id != @user.id %>
                        <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary text-white" %>
                    <% else %>
                            <div>
                                <%= render 'chirps/form', chirp: @chirp %>
                            </div>
                        <% end %>
                <% end %>
            </p> 
        </div>
    </div>

<br>

<br>
<div class="row">
    <div class="col-5"></div>
    <div class="col">
        <% @user.chirps.reverse_each do |chirp| %>
    <div class="d-flex align-items-center">
            <div class="row my-3 " style="background-color: #ebf2ff; width: 500px">
                    <div class="col-xs mx-3 my-2">
                        <% if chirp.user.avatar.attached? %>
                                <%= image_tag (chirp.user.avatar.variant(resize_to_limit: [50,50]))%>
                              <% else %>
                                <%= image_tag("default_avatar.png", :size=>"50x50")%> 
                        <% end%>
                    </div>
                    
                    <div class="col-xs align-self-center">
                        <p >@<%= chirp.user.username %>
                        <%= time_ago_in_words(chirp.created_at) if Time.now - chirp.created_at < 86400 %> 
                        <%= chirp.created_at.strftime('%b %e') if Time.now - chirp.created_at > 86400 %>
                        </p>
                    </div>
                    <div class="col-5 ml-3 my-2" style="width: 450px; background-color: #e1e8f5"><%= chirp.message.html_safe %></div>
                   
                </div> 
            </div>
    
<%end%>
    </div>
</div>

app/views/epicenter/tag_chirps.html.erb
<div>
    <h1><%= @tag.phrase %></h1>
</div>

<br>
  <!-- a place for current user stats -->
  <div class="row">
  <div class="col-3"></div>
  <div class="col">
      <% @tag.chirps.order(created_at: :desc).each do |chirp| %>
        <div class="d-flex align-items-center">
          <div class="row my-3 " style="background-color: #ebf2ff; width: 500px">
              <div class="col-xs mx-3 my-2">
                <% if chirp.user.avatar.attached? %>
                            <%= image_tag (chirp.user.avatar.variant(resize_to_limit: [50,50]))%>
                          <% else %>
                            <%= image_tag("default_avatar.png", :size=>"50x50")%> 
                    <% end%>
                  </div>
              
            <div class="col-xs align-self-center">
              <p >@<%= chirp.user.username %> •
                      <%= time_ago_in_words(chirp.created_at) if Time.now - chirp.created_at < 86400 %> 
                      <%= chirp.created_at.strftime('%b %e') if Time.now - chirp.created_at > 86400 %>
                </p>
            </div>
            <div class="col-5 ml-3 my-2" style="width: 450px; background-color: #e1e8f5"><%= chirp.message.html_safe %></div>
           
        </div> 
      </div>
      <% end %>
  </div> 

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicChirpApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
          <%= link_to "Home", root_path, class: "navbar-brand" %>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0" >
            <li class="nav-item mx-3"> <%=link_to "All Chirps ", chirps_path, class: "text-white" %></li>
            <li class="nav-item mx-3"><%= link_to " Compose New Chirp ", new_chirp_path, class: "text-white" %></li>
            <li class="nav-item mx-3"> <%= link_to " All Users ", all_users_path, class: "text-white" %></li>
          </ul>
          <ul class="navbar-nav ">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle text-white" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                   <% if current_user.avatar.attached? %>
                    <%= image_tag (current_user.avatar.variant(resize_to_limit: [50,50]))%>
                  <% else %>
                    <%= image_tag("default_avatar.png", :size=>"50x50")%> 
                  <% end%>
                  @<%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else%>
              <<li><%= link_to "Sign In", new_user_session_path, class: "text-danger" %> </li>
            <% end%>
          </ul>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>